#!/usr/bin/env bash
# install nginx and configure it to listen to port 80
sudo apt update
sudo apt install nginx -y
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
