#!/usr/bin/env bash
# installs and configures HAProxy in my lb01 server

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 128593-web-01 54.227.197.71 check
    server 128593-web-02 3.85.196.178 check
    option httpchk
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
