#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

# Get the process ID (PID) of the Gunicorn master process
pid=$(pgrep gunicorn)

# Check if the Gunicorn process is running
if [ -z "$pid" ]; then
    echo "Gunicorn is not running."
    exit 1
fi

# Send a HUP signal to the Gunicorn master process for a graceful reload
kill -HUP $pid >/dev/null 2>&1

echo "Gunicorn reloaded gracefully."
exit 0

