#!/usr/bin/env bash
#  reload Gunicorn in a graceful way.

pid=$(pgrep gunicorn)

# Check if the Gunicorn process is running
if [ -z "$pid" ]; then
    echo "Gunicorn is not running."
    exit 1
fi

# Send a HUP signal to the Gunicorn master process to initiate a graceful reload
kill -HUP $pid

echo "Gunicorn reloaded gracefully."
exit 0
